-- datos de prueba

INSERT INTO PROVINCE (province_name) VALUES ('Cartago'),('Heredia'),('San Jose'),('Limon'),('Alajuela'),('Puntarenas'),('Guanacaste')
INSERT INTO CANTON (canton_name, province_id) VALUES ('Marjayoûn', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Jingkou', 3);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Fāqūs', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Shiliting', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('La Unión', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Rumilly', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Auki', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Vimmerby', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Chernyanka', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Yedogon', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Nejo', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Almirante', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Mulanje', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Liulin', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Asopía', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Armenia', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Xidoupu', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Novoye Devyatkino', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Ha', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Biguaçu', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Scholkine', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Sel’tso', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Kishi', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Lisala', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('São Pedro da Aldeia', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Lamía', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Cerenti', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('El Galpón', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Shizikeng', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Surin', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Navais', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Delgado', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Gus’-Zheleznyy', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Marondera', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Saguday', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Melun', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Baiqi', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Marmande', 3);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Pumai', 3);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Bayang', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Cojutepeque', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Xiejiatan', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Guane', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Lingqiao', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Jabinyānah', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Nakhchivan', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Viçosa do Ceará', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Emmaboda', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Rizómata', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('San Diego', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Barnaul', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Īlām', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Safonovo', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Pokrovka', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Osoyoos', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Buçimas', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Vanves', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Padamulya', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Qinghua', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Quimbaya', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Daxing', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Kortesjärvi', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Rizokárpaso', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Dundee', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Hema', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Atuntaqui', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Milltown', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Nishinomiya-hama', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Strömsund', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Rtishchevo', 3);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Selorejo', 3);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Monastir', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Nanjing', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Yarmolyntsi', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Chulakivka', 3);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Kopparberg', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Vitarte', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Zürich', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Drawsko', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Jiuxian', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Shanghu', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Baiqi', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Venustiano Carranza', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Yelwa', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Bāgh-e Maīdān', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Wangzha', 3);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Dawangzhuang', 3);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Passo Fundo', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Tianzhu', 7);
INSERT INTO CANTON (canton_name, province_id) VALUES ('San Jose', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Shymkent', 5);
INSERT INTO CANTON (canton_name, province_id) VALUES ('San Andres', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Jeffersonville', 2);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Aldeia de Juzo', 4);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Angers', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Embarcación', 1);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Energeticheskiy', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Paris La Défense', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Novi Vinodolski', 6);
INSERT INTO CANTON (canton_name, province_id) VALUES ('Sumberejo', 5);

INSERT INTO USER_TYPE (user_type_name) VALUES ('Admin de Campaña'), ('Ciudadano')