USE tempdb
ALTER DATABASE  Caso02_DB2_Esteban_David SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
DROP DATABASE IF EXISTS Caso02_DB2_Esteban_David 
GO
CREATE DATABASE Caso02_DB2_Esteban_David 
GO
USE Caso02_DB2_Esteban_David 

--Create tables

CREATE TABLE PROVINCE(
  province_id INT IDENTITY(1,1) PRIMARY KEY,
  province_name NVARCHAR(100) NOT NULL UNIQUE,
  deleted BIT NOT NULL DEFAULT 0
)

CREATE TABLE CANTON(
  canton_id INT IDENTITY(1,1) PRIMARY KEY,
  canton_name NVARCHAR(250) NOT NULL,
  province_id INT NOT NULL FOREIGN KEY REFERENCES PROVINCE(province_id),
  deleted BIT NOT NULL DEFAULT 0
)

CREATE TABLE USER_TYPE(
  user_type_id INT IDENTITY(1,1) PRIMARY KEY,
  user_type_name NVARCHAR(100) NOT NULL UNIQUE,
  deleted BIT NOT NULL DEFAULT 0
)

CREATE TABLE KPI_TYPE(
  kpi_id INT IDENTITY(1,1) PRIMARY KEY,
  kpi_name NVARCHAR(100) NOT NULL UNIQUE,
  deleted BIT NOT NULL DEFAULT 0
)

CREATE TABLE PARTY(
  party_id INT IDENTITY(1,1) PRIMARY KEY,
  party_name NVARCHAR(250) NOT NULL UNIQUE,
  flag NVARCHAR(500) NOT NULL UNIQUE,
  creation_date SMALLDATETIME NOT NULL,
  foundation DATE,
  deleted BIT NOT NULL DEFAULT 0,
  enabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE PERSON(
  person_id INT IDENTITY(1,1) PRIMARY KEY,
  person_name NVARCHAR(250) NOT NULL,
  lastname NVARCHAR(250) NOT NULL,
  birthdate DATE, 
  id INT NOT NULL UNIQUE,
  creation_date SMALLDATETIME NOT NULL,
  deleted BIT NOT NULL DEFAULT 0,
  enabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE CAMPAIGN_MANAGERS(
  campain_manager_id INT IDENTITY(1,1) PRIMARY KEY,
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id),
  user_bio VARCHAR(1000) NOT NULL,
  photo_url VARCHAR(150) NOT NULL,
  party_id INT NOT NULL FOREIGN KEY REFERENCES PARTY(party_id),
  lastUpdate DATETIME NOT NULL DEFAULT GETDATE(),
  checksum VARBINARY(150) NOT NULL,
  deleted BIT NOT NULL DEFAULT 0,
  enabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE CANTONES_X_USERS(
  cxu_id INT IDENTITY(1,1) PRIMARY KEY,
  canton_id INT NOT NULL FOREIGN KEY REFERENCES CANTON(canton_id),
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id),
  post_update DATETIME NOT NULL DEFAULT GETDATE(),
  canton_default BIT NOT NULL DEFAULT 1,
  deleted BIT NOT NULL DEFAULT 0,
)

CREATE TABLE EMAIL(
  email_id INT IDENTITY(1,1) PRIMARY KEY,
  email NVARCHAR(250) NOT NULL UNIQUE,
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id),
  deleted BIT NOT NULL DEFAULT 0,
  enabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE PHONE(
  phone INT PRIMARY KEY,
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id),
  deleted BIT NOT NULL DEFAULT 0,
  enabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE USER_X_TYPE(
  id INT IDENTITY(1,1) PRIMARY KEY,
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id),
  user_type_id INT NOT NULL FOREIGN KEY REFERENCES USER_TYPE(user_type_id),
  deleted BIT NOT NULL DEFAULT 0,
  enabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE USER_X_GROUP(
  id INT IDENTITY(1,1) PRIMARY KEY,
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id),
  party_id INT NOT NULL FOREIGN KEY REFERENCES PARTY(party_id),
  deleted BIT NOT NULL DEFAULT 0
)

CREATE TABLE PLAN_PARTY(
  plan_id INT IDENTITY(1,1) PRIMARY KEY,
  version_number TINYINT NOT NULL DEFAULT 1,
  title NVARCHAR(200) NOT NULL,
  publish_date DATETIME NOT NULL DEFAULT GETDATE(),
  author_id INT NOT NULL FOREIGN KEY REFERENCES CAMPAIGN_MANAGERS(campain_manager_id),
  checksum VARBINARY(150) NOT NULL,
  deleted BIT NOT NULL DEFAULT 0,
  enabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE ACTION_PLAN(
  action_id INT IDENTITY(1,1) PRIMARY KEY,
  action_title NVARCHAR(100) NOT NULL,
  action_description NVARCHAR(720), 
  plan_id INT NOT NULL FOREIGN KEY REFERENCES PLAN_PARTY(plan_id),
  post_time DATETIME NOT NULL DEFAULT GETDATE(),
  last_update DATETIME NOT NULL DEFAULT GETDATE(),
  version_number TINYINT NOT NULL DEFAULT 1,
  checksum VARBINARY(150) NOT NULL,
  deleted BIT NOT NULL DEFAULT 0,
  enabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE DELIVERABLES(
  delivery_id INT IDENTITY(1,1) PRIMARY KEY,
  action_id INT NOT NULL FOREIGN KEY REFERENCES ACTION_PLAN(action_id),
  plan_id INT NOT NULL FOREIGN KEY REFERENCES PLAN_PARTY(plan_id), 
  canton_id INT NOT NULL FOREIGN KEY REFERENCES CANTON(canton_id),
  kpi_value INT NOT NULL,
  kpi_type INT NOT NULL FOREIGN KEY REFERENCES KPI_TYPE(kpi_id),
  post_time DATE NOT NULL,
  author_id INT NOT NULL FOREIGN KEY REFERENCES CAMPAIGN_MANAGERS(campain_manager_id),
  computer VARCHAR(34) NOT NULL,
  checksum VARBINARY(150) NOT NULL,
  deleted BIT NOT NULL DEFAULT 0,
  enabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE DELIVERABLES_QUALIFICATIONS(
  delivery_qualification_id BIGINT IDENTITY(1,1) PRIMARY KEY,
  canton_id INT NOT NULL FOREIGN KEY REFERENCES CANTON(canton_id),
  delivery_id INT NOT NULL FOREIGN KEY REFERENCES DELIVERABLES(delivery_id),
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id),
  qualification TINYINT NOT NULL CHECK(qualification <= 100),
  checksum VARBINARY(150) NOT NULL,
  deleted BIT NOT NULL DEFAULT 0,
  post_time DATETIME NOT NULL DEFAULT GETDATE(),
  computer VARCHAR(34) NOT NULL
)
