/****** Script for SelectTopNRows command from SSMS  ******/
SELECT	CAMPAIGN_MANAGERS.party_id, DELIVERABLES.action_id, DELIVERABLES.delivery_id, qualification/34 + 1 AS Tercio
FROM [Caso02_DB2_Esteban_David].[dbo].[DELIVERABLES_QUALIFICATIONS]
INNER JOIN DELIVERABLES
ON DELIVERABLES.delivery_id = DELIVERABLES_QUALIFICATIONS.delivery_id
INNER JOIN ACTION_PLAN
ON DELIVERABLES.action_id = ACTION_PLAN.action_id
INNER JOIN PLAN_PARTY
ON PLAN_PARTY.plan_id = DELIVERABLES.plan_id
INNER JOIN CAMPAIGN_MANAGERS
ON PLAN_PARTY.author_id = CAMPAIGN_MANAGERS.campain_manager_id
WHERE DELIVERABLES.action_id = 3
ORDER BY DELIVERABLES.delivery_id

GO 

SELECT party_id,action_id, [0], [1],[2]
FROM 
(
SELECT	CAMPAIGN_MANAGERS.party_id, DELIVERABLES.action_id, DELIVERABLES.delivery_id, qualification/34  AS Tercio
FROM [Caso02_DB2_Esteban_David].[dbo].[DELIVERABLES_QUALIFICATIONS]
INNER JOIN DELIVERABLES
ON DELIVERABLES.delivery_id = DELIVERABLES_QUALIFICATIONS.delivery_id
INNER JOIN ACTION_PLAN
ON DELIVERABLES.action_id = ACTION_PLAN.action_id
INNER JOIN PLAN_PARTY
ON PLAN_PARTY.plan_id = DELIVERABLES.plan_id
INNER JOIN CAMPAIGN_MANAGERS
ON PLAN_PARTY.author_id = CAMPAIGN_MANAGERS.campain_manager_id
WHERE DELIVERABLES.action_id = 3
) AS SOURCE_TABLE
PIVOT
(
	COUNT(Tercio)
	FOR delivery_id  IN ([0],[1],[2])
) AS PIVOT_TABLE;

GO 

SELECT	CAMPAIGN_MANAGERS.party_id, DELIVERABLES.delivery_id, count(qualification/34 + 1 ) AS Tercio
FROM [Caso02_DB2_Esteban_David].[dbo].[DELIVERABLES_QUALIFICATIONS]
INNER JOIN DELIVERABLES
ON DELIVERABLES.delivery_id = DELIVERABLES_QUALIFICATIONS.delivery_id
INNER JOIN ACTION_PLAN
ON DELIVERABLES.action_id = ACTION_PLAN.action_id
INNER JOIN PLAN_PARTY
ON PLAN_PARTY.plan_id = DELIVERABLES.plan_id
INNER JOIN CAMPAIGN_MANAGERS
ON PLAN_PARTY.author_id = CAMPAIGN_MANAGERS.campain_manager_id
WHERE DELIVERABLES.action_id = 3 
GROUP BY party_id, DELIVERABLES.action_id, DELIVERABLES.delivery_id

